name: Create Release

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
      - "babylonjs-*" # Push events to matching babylonjs-*, i.e. babylonjs-(gui)@1.0.0

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: v16.17.0

      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.14.0


      - name: Setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: Install dependencies
        run: pnpm install

      - name: Setup git config
        uses: fregante/setup-git-user@v1

      - name: Read package.json
        uses: tyankatsu0105/read-package-version-actions@v1
        id: package-version

      - name: Get package
        uses: actions/github-script@v6
        id: found-package
        with:
          result-encoding: string
          script: |
            const { getPackages } = require('@manypkg/get-packages')
            const repoPath = process.cwd()
            const { packages } = await getPackages(repoPath)
            const curPkg = packages.find(pkg => context.ref.includes(pkg.packageJson.name))
            const prefixDir = curPkg.dir.replace(repoPath + '/', '')
            return prefixDir

      - name: Create release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          body: |
            Please refer to [CHANGELOG.md](https://github.com/Spencer17x/arca/blob/main/${{ steps.found-package.outputs.result }}/CHANGELOG.md) for details.
